### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by kabiroberai** [open-imcore/imessage-rest#1]
First off, this looks like a really nice project, good work! I was looking through a few files and I found a possible memory leak here: https://github.com/open-imcore/imessage-rest/blob/9b21c90212e1f0ce20ab0e134cb5badb2db738e7/BarcelonaFoundation/SwizzleGenie.swift#L39

`alloc` uses a +1 memory management convention which means it returns retained values – see Apple's [Memory Management Policy](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmRules.html) document. You should use `takeRetainedValue` to consume the unbalanced retain, or else the object will likely end up leaking.

**Comment by EricRabil** [comment]
Thanks for pointing this out! Luckily these methods are no longer used anywhere, so I may end up removing them.

**Comment by EricRabil** [comment]
If you are on the hunt for memory leaks, there _is_ one that is related to IMDPersistence and code that utilizes it.

All calls to IMDPersistence are wrapped at CoreBarcelona/Queries/IMDPersistence.swift

I did my best to follow best practices (i.e. adding the necessary retain annotations to the CF functions in the IMDPersistence headers)

I'll open up a new issue that includes a profiling sample and some traces of the leaked objects.
