### ISSUE TITLE
Build without Mac

### ISSUE THREAD

**Issue by luke2m** [open-imcore/imessage-rest#13]
Is it possible to build this for ios without a Mac? And if so, is this compatible with iOS 9.3.6?

**Comment by CSab6482** [comment]
I'm not the dev but if you're on iOS 9.3.6 (and have a 32 bit device), jailbreak with Phoenix by visiting https://jailbreaks.app from your iOS device, then install [this](https://mega.nz/file/8R1ymaDI#eOtDO_c1RWNRKs5a2EvQExo8nq99mZLTuc2fmgtX9hk).

**Comment by EricRabil** [comment]
This cannot be built without functioning xcodebuild, which, until Darling gets that working, requires a Mac.

Regarding iOS 9, it’s unlikely to work for it as I haven’t tested for compatibility and use iOS 10+ features without compatibility checks.

**Comment by CSab6482** [comment]
> This cannot be built without functioning xcodebuild, which, until Darling gets that working, requires a Mac.
> 
> Regarding iOS 9, it’s unlikely to work for it as I haven’t tested for compatibility and use iOS 10+ features without compatibility checks.

If this works on iOS 10 and 11 you will be liberating so many people stuck in the clutches of SparkDev's Patreon locked AirMessage

**Comment by EricRabil** [comment]
I'll make sure that this works on iOS 10+, although I can't guarantee that it currently runs. YMMV, if anyone tests it on older iOS versions before I do I'd appreciate their crash logs / success stories
